### ISSUE TITLE
VAULT_TLS_SERVER_NAME

### ISSUE THREAD

**Issue by tomalok** [hashicorp/vault-ruby#112]
Will the vault gem eventually understand VAULT_TLS_SERVER_NAME?

(and/or make it easier to perform custom verifications of x509 cert contents?)

**Comment by sethvargo** [comment]
Hey @jefferai 

Do you have some docs you could link to me on this?

**Comment by agperson** [comment]
https://www.vaultproject.io/docs/commands/environment.html

> VAULT_TLS_SERVER_NAME	If set, use the given name as the SNI host when connecting via TLS.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/vault-ruby/pull/131
