### ISSUE TITLE
vault-ruby not compatible with ruby 1.9.3 (puppetserver's jruby)

### ISSUE THREAD

**Issue by jovandeginste** [hashicorp/vault-ruby#114]
I'm upgrading our puppet infrastructure to Puppet 4, and was using the latest vault gem (0.7.x); the puppetserver was complaining about this line:

https://github.com/hashicorp/vault-ruby/blob/fa059fd605695bc8cfc5b7f41b9ddb4c0a0484f7/lib/vault/persistent.rb#L508

The line is not compatible with puppetserver's ruby:
```
=> "jruby 1.7.26 (1.9.3p551) 2016-08-26 69763b8 on OpenJDK 64-Bit Server VM 1.8.0_111-b15 +jit [linux-amd64]"
```

Changed this single line and everything worked:

```ruby
def initialize name = nil, proxy = nil, pool_size = DEFAULT_POOL_SIZE
```

Downgrading the gem to 0.6.0 also fixed the problem.

Is there a good reason to use `name: nil, ...` instead of the compatible `name = nil, ...`?

**Comment by sethvargo** [comment]
Hi there,

That library is actually a forked version of net-http-proxy. I think we can fix this, but please note that the README clearly calls out that Ruby 2.0 is required. We do not test Ruby 1.9 or lower, since it is EOL. https://github.com/hashicorp/vault-ruby#quick-start

**Comment by jovandeginste** [comment]
Yes, I realise the Ruby version in puppet server is dated. Thanks anyway for the fast fix!
