### ISSUE TITLE
Please use POST or PUT with the token passed in via the \"token\" parameter

### ISSUE THREAD

**Issue by pollosp** [hashicorp/vault-ruby#117]
Here is my test code:

```ruby
require 'vault'
Vault.address = 'http://127.0.0.1:8200'
Vault.token   = 'e22577cd-c7d2-0592-7c59-ddc0b3c4a3e4'
p Vault.auth_token.renew('e22577cd-c7d2-0592-7c59-ddc0b3c4a3e4')
```

```shell
vagrant:~/code/vault-test/app$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    vault (0.7.1)
```

My HCL policy:

```hcl
path "secret/*" {
  policy = "write"
}

path "secret/foo" {
  policy = "deny"
}

path "/auth/token/renew/*" {
 policy = "sudo"
}
```

I'm just testing and I'm not really sure about this vault policy maybe it is wrong and that is the problem.

We I execute the code I get the following answer:
```shell
vagrant:~/code/vault-test/app$ bundle exec ruby test.rb
#<Vault::Secret:0x007f99567a86a8 @auth=#<Vault::SecretAuth:0x007f99567a7d98 @accessor="3c95ba7b-1e62-060c-54cd-73f5df5127b7", @client_token="e22577cd-c7d2-0592-7c59-ddc0b3c4a3e4", @lease_duration=35981, @metadata=nil, @policies=["default", "secret"], @renewable=true>, @data=nil, @lease_duration=0, @lease_id="", @renewable=false, @warnings=["Using a token in the path is unsafe as the token can be logged in many places. Please use POST or PUT with the token passed in via the \"token\" parameter."], @wrap_info=nil>
```

[Here](https://github.com/hashicorp/vault-ruby/blob/43a48d3dd1922faa80a70366ba8d36d6b79bbe61/lib/vault/api/auth_token.rb#L148) as you are using PUT, I don't why I'm getting this warning, is this a bug or I'm missing something? 

Thanks in advance :)

**Comment by sethvargo** [comment]
Hi there,

This is something we are aware of, but we cannot make the change just yet. This requires a newer version of Vault, because older versions did not support specifying the token in the body.

**Comment by pollosp** [comment]
Thanks got it 👍

**Comment by sethvargo** [comment]
Hey @pollosp 

Sorry - I didn't mean to imply that we won't do this. Just not quite yet. We need to have a clearer deprecation plan in place for dropping older versions of Vault integration.
