### ISSUE TITLE
mystery error when listing and server response is html

### ISSUE THREAD

**Issue by grosser** [hashicorp/vault-ruby#119]
when the server response is html things get ugly ...

set address to something silly (`http://sddsf.com`) and try to `list` 

```
TypeError - no implicit conversion of Symbol into Integer:
  vault (0.7.1) lib/vault/api/logical.rb:30:in `list'
```

ideally it would blow up nicely and readable as soon as the response is not json

**Comment by sethvargo** [comment]
Hi @grosser 

Thank you for opening an issue. That is going to be true for any response that returns HTML. This tool is designed to communicate with Vault's API, which never returns HTML. As a result, I think raising an error is the appropriate behavior here. Thanks! 😄

**Comment by grosser** [comment]
The point of this issue was that the error is hard to debug.
I'm suggesting to either check the content-type of the reply to be json and raise 'Non json response detected' ... or parse it with JSON and raise when that fails.
Please reopen.
If you agree to one of the approaches I can open a PR
