### ISSUE TITLE
Adding secret backend roles

### ISSUE THREAD

**Issue by russellseymour** [hashicorp/vault-ruby#126]
I am sure this is possible using the gem but I cannot work out how to configure the SSH backend with a role.  For example I need to achieve the following in code.

```
vault write ssh/roles/otp_key_role \
    key_type=otp \
    default_user=username \
    cidr_list=x.x.x.x/y,m.m.m.m/n
```

I have successfully mounted the SSH backend, but how to create the necessary role is eluding me.

**Comment by sethvargo** [comment]
Hi @russellseymour 

I believe you'll want to do this:

```ruby
Vault.logical.write("ssh/roles/otp_key_role", key_type: "otp", default_user: "username")
```

Please let me know if that works.

**Comment by russellseymour** [comment]
Thanks @sethvargo 

That sorted it, all working as I need to now.
