### ISSUE TITLE
No support for the /sys/health endpoint

### ISSUE THREAD

**Issue by CVTJNII** [hashicorp/vault-ruby#137]
In searching the API I don't see support for the [/sys/health endpoint](https://www.vaultproject.io/docs/http/sys-health.html)

```bash
vault-ruby (master) $ git rev-parse HEAD
4740fa418972430e64dc76a14ae5c2d0505e97f5
vault-ruby (master) $ grep -ir health ./
vault-ruby (master) $ 
```

Having access to this endpoint would be useful to check the status of Vault and to know if it's ready.  Specifically I'd like to use this in test situations where I start Vault and then immediately wish to configure it and as such need to block until it is ready.

**Comment by lucymhdavies** [comment]
As a workaround, you could do `Vault.logical.read( "/sys/health" )`

Though this will throw an error if your Vault server is not initialised, unsealed and active.

**Comment by lucymhdavies** [comment]
Or, in my case, I wanted to be able to get the Vault version, regardless of whether Vault itself is Active or Standby.

So I was able to do this with:

```
Vault.get( "/v1/sys/health?standbyok" )
```

**Comment by evanphx** [comment]
This is currently supported.
