### ISSUE TITLE
SSL_CTX_set_cipher_list: invalid command error 

### ISSUE THREAD

**Issue by dasomx77** [hashicorp/vault-ruby#143]
I am running a ruby app (ruby 2.1.9) on ubuntu 12.04 and openssl 1.0.1. Authentication is happening with ssl certificate but when I run the application, setting up the client seems to work fine, but once I attempt to read a secret I get: SSL_CTX_set_cipher_list: invalid command
a snippet of my initializer for the class that is using the library is below:
```ruby
def initialize(opts={})
      # algo = "ECDHE-RSA-AES256-GCM-SHA384:AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES128-GCM-SHA256"
      env = @env = filter_env(opts.fetch(:env, 'test'))
      @server = opts.fetch(:server, config[:server])
      use_ssl = opts.fetch(:use_ssl, config[:use_ssl]) || false
      @cert_path = opts.fetch(:cert_path, config[:cert_path])
      @vault = Vault::Client.new(
        address: @server,
        ssl_pem_file: @cert_path,
        ssl_verify: use_ssl,
        # ssl_ciphers: algo,
        ssl_timeout: 5,
        open_timeout: 5,
        read_timeout: 30
        )
      @vault.auth
    end
```

Utilizing the client to retrieve a secret:
```ruby
@vault.with_retries(Vault::HTTPConnectionError) do
        path = "secret/secretie/#{environment}/#{identifier}"
        value = @vault.logical.read(path)
      end
      raise NotFound.new "Secret #{identifier} was not found in vault under #{@env} environment. current vault cipher: #{@vault.ssl_ciphers}" if value.nil? || value.data.nil?
      if value.data.has_key?(:value)
        {identifier.to_sym => Base64.decode64(value.data[:value]).strip }
      else
        value.data.inject({}) { |decoded_hash, (secret_name, encoded_value)| decoded_hash[secret_name.to_sym] = Base64.decode64(encoded_value); decoded_hash}
      end
```

I have noticed that you have set the default cipher string to 'TLSv1.2:!aNULL:!eNULL' and as you can see it up there, I have been attempting to change the string to find some ciphers that could work with the vault backend which resulted into the service working sometimes and failing at other times (after full restart), when it doesn't work, I get an error saying the vault needs the token to be set. I got he ciphers up there by running:

```bash
for v in ssl2 ssl3 tls1 tls1_1 tls1_2; do
  for c in $(openssl ciphers 'TLS1.2:ALL:!SSLv3!aNull:!eNULL' | tr ':' ' '); do
  echo "trying: $v:\t$c"
    openssl s_client -connect vaultbackend.xxx.xxx:8200 \
      -cipher $c -$v < /dev/null > /dev/null 2>&1 && echo -e "\t$c"
  done
done
```
running: openssl ciphers -v 'TLSv1.2:!eNULL:!aNULL' on the host that should be running this app returns:

```bash
openssl ciphers -v 'TLSv1.2:!eNULL:!aNULL'
Error in cipher list
139913482725024:error:140E6118:SSL routines:SSL_CIPHER_PROCESS_RULESTR:invalid command:ssl_ciph.c:1173:
```
The thing is, I am able to run this app locally on my development machine without any hiccup whatsoever.
Help please!

**Comment by dasomx77** [comment]
By the way, on the host that is running the application and failing, these are the ciphers it seems to support:
```ruby
irb(main):005:0> OpenSSL::Cipher.ciphers
=> ["AES-128-CBC", "AES-128-CBC-HMAC-SHA1", "AES-128-CFB", "AES-128-CFB1", "AES-128-CFB8", "AES-128-CTR", "AES-128-ECB", "AES-128-OFB", "AES-128-XTS", "AES-192-CBC", "AES-192-CFB", "AES-192-CFB1", "AES-192-CFB8", "AES-192-CTR", "AES-192-ECB", "AES-192-OFB", "AES-256-CBC", "AES-256-CBC-HMAC-SHA1", "AES-256-CFB", "AES-256-CFB1", "AES-256-CFB8", "AES-256-CTR", "AES-256-ECB", "AES-256-OFB", "AES-256-XTS", "AES128", "AES192", "AES256", "BF", "BF-CBC", "BF-CFB", "BF-ECB", "BF-OFB", "CAMELLIA-128-CBC", "CAMELLIA-128-CFB", "CAMELLIA-128-CFB1", "CAMELLIA-128-CFB8", "CAMELLIA-128-ECB", "CAMELLIA-128-OFB", "CAMELLIA-192-CBC", "CAMELLIA-192-CFB", "CAMELLIA-192-CFB1", "CAMELLIA-192-CFB8", "CAMELLIA-192-ECB", "CAMELLIA-192-OFB", "CAMELLIA-256-CBC", "CAMELLIA-256-CFB", "CAMELLIA-256-CFB1", "CAMELLIA-256-CFB8", "CAMELLIA-256-ECB", "CAMELLIA-256-OFB", "CAMELLIA128", "CAMELLIA192", "CAMELLIA256", "CAST", "CAST-cbc", "CAST5-CBC", "CAST5-CFB", "CAST5-ECB", "CAST5-OFB", "DES", "DES-CBC", "DES-CFB", "DES-CFB1", "DES-CFB8", "DES-ECB", "DES-EDE", "DES-EDE-CBC", "DES-EDE-CFB", "DES-EDE-OFB", "DES-EDE3", "DES-EDE3-CBC", "DES-EDE3-CFB", "DES-EDE3-CFB1", "DES-EDE3-CFB8", "DES-EDE3-OFB", "DES-OFB", "DES3", "DESX", "DESX-CBC", "RC2", "RC2-40-CBC", "RC2-64-CBC", "RC2-CBC", "RC2-CFB", "RC2-ECB", "RC2-OFB", "RC4", "RC4-40", "RC4-HMAC-MD5", "SEED", "SEED-CBC", "SEED-CFB", "SEED-ECB", "SEED-OFB", "aes-128-cbc", "aes-128-cbc-hmac-sha1", "aes-128-cfb", "aes-128-cfb1", "aes-128-cfb8", "aes-128-ctr", "aes-128-ecb", "aes-128-gcm", "aes-128-ofb", "aes-128-xts", "aes-192-cbc", "aes-192-cfb", "aes-192-cfb1", "aes-192-cfb8", "aes-192-ctr", "aes-192-ecb", "aes-192-gcm", "aes-192-ofb", "aes-256-cbc", "aes-256-cbc-hmac-sha1", "aes-256-cfb", "aes-256-cfb1", "aes-256-cfb8", "aes-256-ctr", "aes-256-ecb", "aes-256-gcm", "aes-256-ofb", "aes-256-xts", "aes128", "aes192", "aes256", "bf", "bf-cbc", "bf-cfb", "bf-ecb", "bf-ofb", "blowfish", "camellia-128-cbc", "camellia-128-cfb", "camellia-128-cfb1", "camellia-128-cfb8", "camellia-128-ecb", "camellia-128-ofb", "camellia-192-cbc", "camellia-192-cfb", "camellia-192-cfb1", "camellia-192-cfb8", "camellia-192-ecb", "camellia-192-ofb", "camellia-256-cbc", "camellia-256-cfb", "camellia-256-cfb1", "camellia-256-cfb8", "camellia-256-ecb", "camellia-256-ofb", "camellia128", "camellia192", "camellia256", "cast", "cast-cbc", "cast5-cbc", "cast5-cfb", "cast5-ecb", "cast5-ofb", "des", "des-cbc", "des-cfb", "des-cfb1", "des-cfb8", "des-ecb", "des-ede", "des-ede-cbc", "des-ede-cfb", "des-ede-ofb", "des-ede3", "des-ede3-cbc", "des-ede3-cfb", "des-ede3-cfb1", "des-ede3-cfb8", "des-ede3-ofb", "des-ofb", "des3", "desx", "desx-cbc", "id-aes128-GCM", "id-aes192-GCM", "id-aes256-GCM", "rc2", "rc2-40-cbc", "rc2-64-cbc", "rc2-cbc", "rc2-cfb", "rc2-ecb", "rc2-ofb", "rc4", "rc4-40", "rc4-hmac-md5", "seed", "seed-cbc", "seed-cfb", "seed-ecb", "seed-ofb"]
```

**Comment by sethvargo** [comment]
From what I understand, Ubuntu 12.04 is currently beyond "maintenace-only" mode expect for Ubuntu Advantage customers. As such, I'm not surprised it does not have the latest cipher suites.

**Comment by dasomx77** [comment]
:D fun seeing you here as well. I recall reading some of your post from Chef I believe. To get back to the issue, yes, we are working on updating it to a newer version (hopefully sooner than later). But on that note as well, I have realized that with my custom cipher preference string I do get some hits then sometimes plainly get "Vault isn't set with a token" (I am assuming this happens when a cipher is chosen that vault doesn't support?) but it looks like out of the ciphers currently supported by the node, there is at least one that works with both ends. I am still learning my way around tls so pardon the jargon...

**Comment by sethvargo** [comment]
Vault only allows TLS 1.2 by default. You can configure the Vault server to accept older ciphers: https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_min_version

**Comment by dasomx77** [comment]
Thanks! I see [here](https://golang.org/src/crypto/tls/cipher_suites.go) that AES128-GCM-SHA256 is supported as cipher, would it help if I overwrite my vault client cipher variable to be strictly that instead of reducing vault's min tls version?

**Comment by dasomx77** [comment]
So we have reduced the min version in our backend but I am still seeing this error:
Missing Vault token! I cannot make requests to Vault without a token. Please set a Vault token in the client: Vault.token = xxx... 
That is with a cipher preference string: 'TLSv1:!eNULL:!aNULL'

**Comment by lirao** [comment]
( @dasomx77 's teammate here)
We are using vault 0.7.0 if you need that info

**Comment by dasomx77** [comment]
@sethvargo we just realized why it never worked on the end server, it seems on my development machine, I always had a cli session with vault (=> a .vault-token was always present) which inherently made me assume that just instantiating the client would generate a token, and therefore never called the vault.auth.tls part in the first place. Thanks for helping us!!
