### ISSUE TITLE
Lease renew is inconsistent with the API docs and results in permissions denied.

### ISSUE THREAD

**Issue by mitom** [hashicorp/vault-ruby#145]
The API [documents](https://www.vaultproject.io/api/system/renew.html#renew-lease) the lease renew endpoint as `/v1/sys/renew` with a payload of
```json
{
  "lease_id": "aws/creds/deploy/abcd-1234...",
  "increment": 1800
}
```
Which works as expected:
```
curl --request PUT \
  --url https://vault.example.com/v1/sys/renew \
  --header 'content-type: application/json' \
  --header 'x-vault-token: ****' \
  --data '{"lease_id": "consul/creds/***/***", "increment": 18000}'
{"request_id":"e040b07a-eb9a-c8d5-10dc-7b1f45272e02","lease_id":"consul/creds/***/***","renewable":true,"lease_duration":18000,"data":null,"wrap_info":null,"warnings":null,"auth":null}
```

The API used is `/v1/sys/renew/{id}`: https://github.com/hashicorp/vault-ruby/blob/b256513517abc2b31cc177b5378dc9ba2457ae78/lib/vault/api/sys/lease.rb#L13-L18

Results in:
```
curl --request PUT \
  --url https://vault.example.com/v1/sys/renew/consul/creds/***/*** \
  --header 'content-type: application/json' \
  --header 'x-vault-token: ****' \
  --data '{"increment": 18000}'
{"errors":["permission denied"]}
```

**Comment by jefferai** [comment]
I recommend actually holding off changing this in vault-ruby until the next release of Vault in late July since what we want to move towards is using `sys/leases/renew` but there's a bug in that endpoint right now. As a user you can work around this at the moment by modifying your policy.

**Comment by mitom** [comment]
Could you please explain what bug is there in the renew endpoint at least for reference? Using an undocumented endpoint is quite bad, need to justify somehow.

**Comment by jefferai** [comment]
@mitom the endpoint is still there for backwards compatibility.

**Comment by mitom** [comment]
@jefferai while that may be true, it's still not in the documentation, not even in a deprecated state while the documentation explicitly warns about backwards compatibility not being guaranteed. The [vault binary also uses](https://github.com/hashicorp/vault/blob/master/api/sys_lease.go#L3-L8) the `/v1/sys/renew` endpoint. I am curious as to what is the bug you mentioned that is a reason against it, partially because by using `vault renew` I am using the new endpoint and would be good to know the risks/consequences.

It also causes the library to behave differently than how the binary behaves which I'd assume is the goal for parity. While I understand that this can be negated by changing policies, my opinion is given that the binary already uses the endpoint and therefore it's very likely that most of the userbase is as well I'd rather have parity than having to work around different implementations.

I am happy to submit a PR if that helps with this, but if it wouldn't get merged anyway until late july, it would be good to at least understand the reason behind it as if that bug is this serious, the solution might be for me to stop using the new endpoint entirely until that's fixed.

**Comment by jefferai** [comment]
I'm sorry, I really am just not understanding what the issue is.

The Vault binary uses `sys/renew`. The Vault Go API uses `sys/renew`. The Vault website documents `sys/renew`.

It looks like your policies simply don't allow the endpoint that vault-ruby is using.

**Comment by mitom** [comment]
>It looks like your policies simply don't allow the endpoint that vault-ruby is using.
That is correct, due to the fact that vault-ruby is using an endpoint that is not officially documented and behaves differently than the officially documented endpoint to perform this action (renew a lease). As I have shown in my original comment, using the API vault-ruby uses results in a `permission denied` error. Using the same token, with the same policies to renew the same lease results in successfully renewing the lease using the API that is documented on the Vault website.

The issue is that attempting to use vault-ruby at the moment requires different policies than using the documented Vault API to perform the same action. You mentioned that the method vault-ruby uses should not be updated (which would resolve the issue of different policies being required than using the API/binary/any other component with vault) due to a bug in the current Vault API, which could be reasonable, but if there is such a serious bug I'd want to know what that is (do you have an issue link or something maybe..?). As vault deals with secrets it is very important to be clear about known issues with it, especially if they seem serious enough to hold back an official library from using part of the API.

I am sorry if I fail to make myself clear, I am unsure how to further explain my problem. Essentially I'd like one of 2 things to happen:
1. get information on *why* the new API shouldn't be used to assess the risk of using it with other components
2. get vault-ruby updated to use the new API to behave the same as the binary/API within the same environment to perform the same action (as in same policies, token, arguments should be able to renew the token in both the binary and the library).

Is there any way I can explain it further or something I can do to help?

**Comment by jefferai** [comment]
> due to the fact that vault-ruby is using an endpoint that is not officially documented

It's documented.

> The issue is that attempting to use vault-ruby at the moment requires different policies than using the documented Vault API to perform the same action.

There are multiple ways that lease renewal can be achieved, even using the same `sys/renew` endpoint -- the lease ID can be passed in via the URL, or it can be passed in via the request body. At any given time vault-ruby is going to be using one or the other. If your policies only allow the other one, it will fail.

This is a super easy fix. If you want to allow both methods, update your policies to allow both methods.

Otherwise, you could suggest that vault-ruby switch over to the other method, but I'm not sure that's any better as that might then affect others with different policies.

**Comment by mitom** [comment]
> It's documented.

where?

**Comment by jefferai** [comment]
https://www.vaultproject.io/api/system/renew.html

**Comment by mitom** [comment]
That is the documentation I was referring to. It documents the method as the path being `/sys/renew` (note, no parameters) and the payload as 
```
{
  "lease_id": "aws/creds/deploy/abcd-1234...",
  "increment": 1800
}
```
(note the lease_id is in the payload)

The [usage in vault-ruby](https://github.com/hashicorp/vault-ruby/blob/b256513517abc2b31cc177b5378dc9ba2457ae78/lib/vault/api/sys/lease.rb#L13-L18) is different.
```
      json = client.put("/v1/sys/renew/#{id}", JSON.fast_generate(
        increment: increment,
      ))
```
(Note the lease id is passed in the path, not in the payload as on the documentation).

To me that means a different API or using it wrong, and I have a use case where their behaviour can be shown to be different. Am I missing something here?

**Comment by sethvargo** [comment]
Hi @mitom 

If you take a close [look at the documentation](https://www.vaultproject.io/api/system/renew.html), you'll see that under `lease_id`, it says:

> ... This can be specified as part of the URL or as part of the request body.

It's valid to pass it as part of the request body _or_ part of the URL. Originally Vault only permitted the URL, which is why this client library still only uses the URL, for BC reasons. Once we drop support for old Vaults (soon), we can force users onto the new method.

**Comment by mitom** [comment]
@sethvargo thank you you are right I did miss that! Is there any reason why the behaviour is different depending whether it's part of the body or the url?

**Comment by sethvargo** [comment]
The behavior isn't different, but the policy is. If specified as part of the URL, your policy has to allow for `sys/renew/*`, whereas if specified as part of the body, you only need `sys/renew`.

**Comment by mitom** [comment]
Ah I see! My confusion stems from the fact that the default policy allows `update` for the `sys/renew` endpoint. 

Thank you for clearing it up, I am sorry for the misunderstanding @jefferai .
