### ISSUE TITLE
No support for setting base_url/organization for Github auth

### ISSUE THREAD

**Issue by ngunia** [hashicorp/vault-ruby#148]
Hi,

Trying to set up a multi-tenant vault cluster, using GitHub orgs to separate and some scripts to setup.  I can do everything I need to just fine with this lib, except for configuring the Vault GitHub auth backend with a base_url and organization name.  Currently I just print a command to run separately in a CLI.  I would like to make this process self service.  It looks like there are endpoints to tune this backend, but according to the docs I should only be able to modify the default_lease_ttl/max_lease_ttl.  [This endpoint ](https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/sys/auth.rb#L107 )works for neither:

```
2.3.3 :021 > Vault.sys.auth_tune("github")
 => #<Vault::AuthConfig:0x007fe9620e1c00 @default_lease_ttl=2764800, @max_lease_ttl=2764800>
2.3.3 :022 > Vault.sys.put_auth_tune("github", default_lease_ttl => 2764799)
 => true
2.3.3 :023 > Vault.sys.auth_tune("github")
 => #<Vault::AuthConfig:0x007fe9620f0b10 @default_lease_ttl=2764800, @max_lease_ttl=2764800>
```

I am unclear whether I should be able to set base_url and organization here, but I can't set anything at all.  Is there another lib method I should be using, or is it currently unsupported by the API? I'd be glad to take a stab at adding the endpoint if needed, after a bit more research. Thanks!

**Comment by sethvargo** [comment]
Hi @ngunia 

You write to `auth/github/config`, the same way you do to configure it via the Vault CLI:

```ruby
Vault.logical.write("auth/github/config", base_url: "...")
```
