### ISSUE TITLE
Update for vault 0.8

### ISSUE THREAD

**Issue by SarahRiley** [hashicorp/vault-ruby#151]
Vault 0.8 has been released, including deprecating the endpoints `sys/renew, sys/revoke, sys/revoke-prefix, sys/revoke-force`.

When will this library be updated to support that?

**Comment by sethvargo** [comment]
Hey @SarahKowalik 

Thank you for opening the PR. We are happy to update those, but we have to consider that such a change would break for Vault users who haven't updated their clusters. I think we can do it, we just have to mark it as a breaking change.
