### ISSUE TITLE
[AWS Auth Backend IAM user ] Support to generate the vault signature in format required for VAULT API's 

### ISSUE THREAD

**Issue by siddheshwar-more** [hashicorp/vault-ruby#157]
Is there any ruby sdk way which generates the signature same like - https://github.com/aws/aws-sdk-go/blob/master/aws/signer/v4/v4.go#L654-L662 

The generated signature used with Vault Login API's to get the token using IAM users creds.

**Comment by sethvargo** [comment]
Work is being done in https://github.com/hashicorp/vault-ruby/pull/144
