### ISSUE TITLE
lease renewal and revocation does not work

### ISSUE THREAD

**Issue by dansteen** [hashicorp/vault-ruby#158]
It looks like the library is trying to call: `sys/renew` and `sys/revoke..` when it should be calling `sys/leases/renew` and sys/leases/revoke..` per the docs here: https://www.vaultproject.io/api/system/leases.html

relevant code is here: https://github.com/hashicorp/vault-ruby/blob/4780e8930cd339732906b6d433f9bdf3bb2bb88e/lib/vault/api/sys/lease.rb#L14

and here:
https://github.com/hashicorp/vault-ruby/blob/4780e8930cd339732906b6d433f9bdf3bb2bb88e/lib/vault/api/sys/lease.rb#L31

and here:
https://github.com/hashicorp/vault-ruby/blob/4780e8930cd339732906b6d433f9bdf3bb2bb88e/lib/vault/api/sys/lease.rb#L45

Thanks!

**Comment by jefferai** [comment]
The old path is still supported for backwards compatibility. What is the issue you are seeing?

**Comment by dansteen** [comment]
So, I suppose it's more of a documentation issue then.   The trouble is that if I provide policy permissions for `sys/leases/renew` they (reasonably) won't be applied to `sys/renew`.   However, there is no way for me to know that I need to grant permissions for `sys/renew` as well - as it's no longer mentioned anywhere in the docs.   So I get errors and have to dig through the code to figure out what the issue is.

**Comment by jefferai** [comment]
Ah, okay. Generally we remove documentation for old paths, probably the right thing to do is in fact update it in the gem. At least it's not a regression in Vault (phew 😀)
