### ISSUE TITLE
Using in Vagrantfile

### ISSUE THREAD

**Issue by zelentsovl** [hashicorp/vault-ruby#163]
Hello everyone!

Does anybody know whether it's possible to use the library from Vagrantfile? I have installed:
ruby 2.0.0p648
Vagrant 2.0.1
vault (0.10.1) (via gem install)

On attempt of using:
 Vault.address = ENV["VAULT_ADDR"]

i get the error:   "uninitialized constant Vault (NameError)"

Thank you in advance!

**Comment by evanphx** [comment]
Are you trying to reference `Vault.address` within the Vagrantfile itself? If so, why?

**Comment by zelentsovl** [comment]
In order to set address of external vault instance and pull some secrets from it to some variable.

**Comment by evanphx** [comment]
I mean, do you want vagrant to be talking to vault? You have to get the gem into vagrant's gem dir and then `require "vault"`. Are you doing that?

**Comment by zelentsovl** [comment]
- require "vault" - yes
- get the gem to vagrant’s gem dir - no

Thanks for advice!
