### ISSUE TITLE
custom auth mount points for aws-ec2 auth.

### ISSUE THREAD

**Issue by jamengual** [hashicorp/vault-ruby#164]
Hi.

We have multiple Aws accounts using our vault server and for each one we have configured a custom mount point like so : 

curl -w "%{http_code}" --header "X-Vault-Token: REDACTED" --request POST --data @aws-auth-ec2-preprod.json  $VAULT_ADDRESS/v1/sys/auth/aws-preprod

so for each aws account we have a different mount point but the library assumes that the mount point should be  /v1/auth/aws-ec2/login which it does not work with custom mount points.

This is the specific code line : 

https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/auth.rb#L183

Is there a reason why is hardcoded ? 

should we be using one moun point instead of one per account ?

**Comment by evanphx** [comment]
@jefferai @briancain Could use some guidance on this one.

**Comment by evanphx** [comment]
@briankassouf Could use some guidance on this one.

**Comment by briancain** [comment]
Hi @jamengual ! I'm not too familiar with the Vault API, but if I am understanding this correctly, it seems like Vault allows for custom mount points, and if so, this function should take that into account. If that's the case then I think it makes sense for this function to take an optional parameter which is a custom mount point to use, and default to what it currently is. Does that make sense?

**Comment by jamengual** [comment]
@briancain that is correct due to Vault supporting custom mount point this function I think should support it and yes the default could be what is currently in code and have the option to change it. Kudos to @rhealauzon for finding this.

**Comment by briancain** [comment]
I've made a pull request that updates the method with an optional `route` parameter.
