### ISSUE TITLE
support auth_type GCP/GCE

### ISSUE THREAD

**Issue by evralston** [hashicorp/vault-ruby#165]
Google cloud authentication in the spirit of #161 e.g. without bringing in heavy libraries

Docs:
https://www.vaultproject.io/docs/auth/gcp.html
https://www.vaultproject.io/api/auth/gcp/index.html

Looks like a fork has done some work toward this: https://github.com/wayfair/vault-ruby/tree/add-gcp-auth

**Comment by evralston** [comment]
Happy to put this together, but opening an issue first in case it flushes out anyone else who's started on it.

**Comment by evanphx** [comment]
@evralston If you can submit a PR for it, that would be great! Thanks!

**Comment by evanphx** [comment]
#173 was added to address this.
