### ISSUE TITLE
Using aws_ec2 to Auth isn't clear in the ReadME file

### ISSUE THREAD

**Issue by Morxander** [hashicorp/vault-ruby#169]
Hey guys,

I'm trying to use `aws_ec2` role to auth to my vault server, it's working fine on my local machine using `vault token` but on my server I am not sure how to make it works.

This is my code for my dev machine : 

    vault_data_client = Vault::Client.new(address: ENV["VAULT_ADDR"], token: ENV["VAULT_TOKEN"])
    vault_data_client.logical.read('secret/project/global').data

and for my server this my code : 

    vault_data_client = Vault.auth.aws_ec2('application-role', signature, nil)
    vault_data_client.logical.read('secret/project/global').data

Then I discovered that the `aws_ec2` returns `Vault::Secret` and not `Vault::Client` like `Vault::Client.new` so now how can I read the secrets for specific project/profile?

**Comment by Morxander** [comment]
I managed to make it work and I wrote a small section to explain it in the README here : https://github.com/hashicorp/vault-ruby/pull/171

**Comment by evanphx** [comment]
Fixed via doc change!
