### ISSUE TITLE
vault-ruby cannot write secrets to vault server, version >=0.10.0

### ISSUE THREAD

**Issue by arecker** [hashicorp/vault-ruby#182]
Writing a secret with the CLI:

```
root@bootstrap-ubuntu-1604:~# vault version
Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
root@bootstrap-ubuntu-1604:~# vault kv put secret/bacon "delicions=true,cooktime=11"
Key              Value
---              -----
created_time     2018-08-07T20:42:02.333492408Z
deletion_time    n/a
destroyed        false
version          1
```

Writing a secret with vault-ruby:

```
[1] pry(main)> require 'vault'
[2] pry(main)> client = Vault::Client.new(address: 'http://127.0.0.1:8200', token: File.read('/root/.vault-token'))
[3] pry(main)> client.logical.write("secret/bacon", delicious: true, cooktime: "11")
Vault::HTTPClientError: The Vault server at `http://127.0.0.1:8200' responded with a 404.
Any additional information the server supplied is shown below:

  * {"request_id":"7e8e4d50-4972-2129-4dc4-4e0c7ef37db9","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put' for this operation."],"auth":null}
```

The last version of vault that still works is 0.9.6.

**Comment by evanphx** [comment]
@jefferai Is this an API change in vault that the gem needs to address?

**Comment by jefferai** [comment]
Basically it depends if it's a kvv1 or kvv2 mount. They have different APIs.

**Comment by jefferai** [comment]
It looks like they're using a generic write method, in which case they just need to use the correct path/args.

**Comment by geek65535** [comment]
According to the API docs, a V2 write should be in this form:
https://127.0.0.1:8200/v1/secret/data/my-secret
But that doesn't work:
[17] pry(main)> client.logical.write("secret/data/bacon", delicious: true, cooktime: "11")
Vault::HTTPClientError: The Vault server at `http://127.0.0.1:8200' responded with a 400.
Any additional information the server supplied is shown below:

  * no data provided

Please refer to the documentation for help.
from /var/lib/gems/2.5.0/gems/vault-0.12.0/lib/vault/client.rb:400:in `error'

**Comment by v6** [comment]
// , @Zeerg, do reads work when you add `/data` to the Vault KV Path?

**Comment by jefferai** [comment]
@Zeerg depends if it's KV v1 or KV v2.

**Comment by Zeerg** [comment]
@v6 @jefferai I just switched to KV v1

**Comment by noma4i** [comment]
@geek65535 now I should admit that I suffer w/o v2 support. 

Unfortunately offical libraries are poorly supported.

**Comment by grosser** [comment]
@evanphx do you know if support for v2 in the ruby client is planned / in the works ?

**Comment by evanphx** [comment]
A better question for @chrishoffman

**Comment by grosser** [comment]
possible fix https://github.com/hashicorp/vault-ruby/pull/188

**Comment by grosser** [comment]
can someone merge or comment on what needs to change ?

**Comment by v6** [comment]
// , Posted about this here: https://groups.google.com/forum/#!topic/vault-tool/8QeMOjYZjzk

**Comment by notjames** [comment]
> I had this issue as well. The api expects it to be `{ "data": { "foo": "bar", "zip": "zap" } }`
> 
> So I just added my secrets like this `client.logical.write("secret/data/bacon", data : { delicious: true, cooktime: "11"})`

Looks like when this method (use of `data: ...`) is used, the secret is written to vault as a JSON object and cannot be switched to kv pairs. :\

**Comment by notjames** [comment]
> > I had this issue as well. The api expects it to be `{ "data": { "foo": "bar", "zip": "zap" } }`
> > So I just added my secrets like this `client.logical.write("secret/data/bacon", data : { delicious: true, cooktime: "11"})`
> 
> Looks like when this method (use of `data: {...}`) is used, the secret is written to vault as a JSON object and cannot be switched to kv pairs. :\
> 
> I wonder if I can monkeypatch the write method to handle kv v2... hmm.

OK, I was gonna delete my previous comment but I think I was wrong. I was able to get it to work using `data: <hash>` then it seems to function correctly. e.g.
```
some_hash = { :key1 => 'foo', :key2 => 'bar'}
client.logical.write("secret/data/bacon", data : some_hash)
```

this: `client.logical.write("secret/data/bacon", data : { delicious: true, cooktime: "11"})` caused a json entry to occur. I'm still not sure why.

**Comment by swenson** [comment]
This sounds like it was a invalid path issue, and not an error in `vault-ruby`, so I'm closing this for now.
