### ISSUE TITLE
client.logical.read cannot read k/v version 2 secrets

### ISSUE THREAD

**Issue by sriedel** [hashicorp/vault-ruby#193]
After switching vaults key/value store from version 1 to version 2 in order to activate the versioning functionality, the ruby client could no longer access the (only) version of a key's value, and returned nil instead.

Would it be possible to throw an exception in this case, in order to make it clear what the issue is? Just returning nil gives the impression that the key no longer has a value associated with it, making it easy to come to a wrong conclusion as to what is happening and why.

**Comment by grosser** [comment]
see https://github.com/hashicorp/vault-ruby/issues/182

**Comment by sriedel** [comment]
Thank you.  :)
Closing as duplicate.
