### ISSUE TITLE
Unable to use tls certificate auth backend

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/vault-ruby#23]
I cant use the tls certificate auth backend, because one can not set a separate key file.

See https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/client.rb#L192

**Comment by dkaffee92** [comment]
Hey @kaelumania, that's not entirely true, what you have to do is concatenate your certificate and private key and use 
```ruby
ssl_pem_file.path = File.read("/path/to/concatenated/file")
```

another solution (even though quite dirty) is either create the file on the fly or use a Tempfile that will be garbage collected (even though it is probably less safe)

```ruby
ssl_pem_file = Tempfile.new("ssl_pem_file")
ssl_pem_file.write File.read("/path/to/internal.cert")
ssl_pem_file.write File.read("/path/to/internal.key")
ssl_pem_file.close

Vault.configure do |vault|
  vault.ssl_pem_file = ssl_pem_file.path
end
```

**Comment by kaelumania** [comment]
Thanks, i didn't know that its possible to concatenate both files. But i think it's more clean to have both files separated, because maybe you wanna provide a passphrase for the keyfile.

**Comment by dkaffee92** [comment]
You can still use a single file when you have a passphrase, openssl knows how to handle it, problem is that the vault-ruby client doesn't have the option to add your passphrase.
Why would you want a passphrase on these certificates anyway? They are deployed to your server ... it doesn't make much sense ...

**Comment by kaelumania** [comment]
@dkaffee92 I don't think that these certificates are being deployed, because this is a client side configuration. Further I wondered for what these certificates are good for, because you can not configure a certificate authority on server side. Therefore the server has no clue how to authenticate a request. If I understand vault right, this is only done via tokens. The only feature that requires client side certificates is the TLS auth backend in order to register a user and obtain a token.

I am currently building a little tool around vault and using the TLS auth backend. Whenever a token expires I need to request a new token via TLS auth backend, but I want the user to explicitly enter his passphrase (its more secure and explicit). Or do you have any other suggestions?

**Comment by d3-btr** [comment]
I'm not even seeing where the `vault-ruby` library has the TLS Certificates Auth Backend implemented. For example, in `lib/vault/api/auth.rb` I'm not seeing a request method that makes a post to `/v1/auth/cert/login`. Am I missing something?

**Comment by activeshadow** [comment]
I'm not even seeing where the `vault-ruby` library has the TLS Certificates Auth Backend implemented. For example, in `lib/vault/api/auth.rb` I'm not seeing a request method that makes a post to `/v1/auth/cert/login`. Am I missing something?

**Comment by sethvargo** [comment]
Hi all,

I think there is some confusion here and @activeshadow is correct. The `ssl_pem_file`, `ssl_ca_cert`, and `ssl_ca_path` options are for specifying _client_ certificates for communicating with Vault via SSL. If you're running Vault over SSL (as you should), but you are using a self-signed certificate or a certificate that is not trusted by the client OS, you need to point to the correct CA to verify. That's what those are used for.

The TLS certificate backend is not something that the Vault Ruby client supports out of the box. You can easily make the required API calls using `client.post` until we get that implemented.

**Comment by kaelumania** [comment]
I think vault does not support client certificates for SSL communication with the Vault itsself - it just allows you to verify its SSL certificate via your (self-signed) CA. But the cert auth backend requires to you set `ssl_pem_file`. I think this is confusing, because the Vault CLI lists `ssl_pem_file` as global option.

**Comment by filipecabaco** [comment]
What's the status of this issue?

**Comment by kaelumania** [comment]
@filipecabaco I did a PR and its waiting for @sethvargo to be merged

**Comment by sethvargo** [comment]
https://github.com/hashicorp/vault-ruby/pull/94
