### ISSUE TITLE
New release of gems?

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault-ruby#24]
Would it be possible for a new release of `vault` and `vault-rails` to be cut? Our app depends on some of the more recent changes.

**Comment by sethvargo** [comment]
Hi @BRMatt 

Soon(tm) - for now, you can use Bundler to point to a specific GitHub repo or the commit SHA you need on each project. Thanks!

**Comment by BRMatt** [comment]
Thanks, yep that's what we're doing at the moment. It's just awkward as we have a shared gem that contains all our models, so each app that uses the gem needs to separately specify that it wants to use vault-ruby from github rather than rubygems.
