### ISSUE TITLE
vault-ruby substitute for /v1/auth/cert/login with a role

### ISSUE THREAD

**Issue by khawkins** [hashicorp/vault-ruby#254]
Per [the docs](https://www.vaultproject.io/docs/auth/cert) on TLS-based authentication, the `/v1/auth/cert/login` API endpoint accepts a role for the cert being used to authenticate. However, the [`Vault.auth.tls()` method](https://github.com/hashicorp/vault-ruby/blob/dac98febad779048bfa24c6452a946fd979754cf/lib/vault/api/auth.rb#L290) does not appear to support this input. And it seems to be required in our case as, if we authenticate with the `tls()` method, while we do successfully authenticate and get back an auth token, subsequent attempts to use it to authorize our requests fail with a 403. This doesn't happen if we use the token garnered from hitting the API endpoint directly (i.e. a raw HTTP request), specifying the proper role as part of process.

Could someone point out if I'm missing something obvious, or suggest another preferred workflow for using vault-ruby to get a token authorized for such a role? Thank you in advance!

**Comment by khawkins** [comment]
Never mind. Turns out we were using the token wrong. I had the following code to set our token:
```ruby
 vault_token = Vault.auth.tls
 Vault.token = vault_token  # This is the problem
 secrets = Vault.kv('our_prefix').read('our_key_path')
```

`Vault.auth.tls` returns a `Vault::Secret`, while the token of `Vault::Client` is just a string, and we should be using `secret.auth.client_token` for that value instead. That's why we were getting 403s when using our token. I figured I'd document it here for posterity, in case someone else makes the same misstep.

**Comment by khawkins** [comment]
Actually, while the above misstep is legitimate, the underlying issue is still there. It didn't come up for me in my test use case because I was testing against a vault with only one role, so it worked.

If you can't specify the role as part of authentication, you're at the mercy of returning credentials for whatever the default role is. If that's not the right role, you're out of luck.

This seems like a bug to me, unless there's another way to supply the role, after authentication. But it seems too late in the process to do so, to me.

**Comment by Valarissa** [comment]
Hey there, just wanted to let you know I'm taking a look at this.

**Comment by calvn** [comment]
Apologies for the delay on this! The PR has been merged and should be available in the next release.
