### ISSUE TITLE
last release 0.16.0 is quite old.

### ISSUE THREAD

**Issue by fabio42** [hashicorp/vault-ruby#267]
Hi,

I'm wondering if there is any plan to release a new version of this gem ? 
Last release (0.16.0) is more than a year old now, and we are looking at feature that have long been addressed (ie [PR 256](https://github.com/hashicorp/vault-ruby/pull/256)) and that is well documented.
Would be nice to have a release bringing these changes without having to package it ourselves or worst work around.

Thank you !

**Comment by rjhornsby** [comment]
Given the recent 0.17.0 release, this can probably be closed for the sake of tidiness.

**Comment by fabio42** [comment]
Thank you for releasing a new version !
