### ISSUE TITLE
vault 0.18.2 ruby released but no changelog

### ISSUE THREAD

**Issue by broksonic21** [hashicorp/vault-ruby#316]
Vault https://github.com/hashicorp/vault-ruby/releases/tag/v0.18.2 was released but the changelog is missing info on it: https://github.com/hashicorp/vault-ruby/blob/master/CHANGELOG.md

Can you fill us in on what it is? thanks!

**Comment by yoda** [comment]
https://github.com/hashicorp/vault-ruby/compare/v0.18.1...v0.18.2

**Comment by broksonic21** [comment]
closing older ticket given above feedback.
