### ISSUE TITLE
Use github auth method

### ISSUE THREAD

**Issue by parabuzzle** [hashicorp/vault-ruby#33]
So, maybe I'm blind but with the cli I can do:

```
vault auth -method=github -token=1234...
```

But I don't see a way to use alternate auth methods (github in particular)

**Comment by sethvargo** [comment]
@parabuzzle you can use a few - https://github.com/hashicorp/vault-ruby/blob/master/lib/vault/api/auth.rb, but GitHub isn't currently a first-class one. 

The good news is that auth is pretty easy - it's just an HTTP POST request to the mounted endpoint.

**Comment by parabuzzle** [comment]
I may just add it after work and contrib back then :)

**Comment by sethvargo** [comment]
@parabuzzle thanks :smile: 

For what it's worth, the reason I didn't do it was testing purposes. There's really no good way to integration test it.

**Comment by parabuzzle** [comment]
@sethvargo good question... how strict does integration testing have to be? would it be ok to just stub out the github api calls in the test? (although that may be more work than its worth here)

**Comment by sethvargo** [comment]
Stubs are fine, I just didn't have the time to do it correctly :smile:

**Comment by parabuzzle** [comment]
Ok, I'm stumped... 

I can't find a way to override the Github auth api in the vault server. It seems to only point to `api.github.com`. 

My original thinking was to standup a simple webrick that talks the github api and point the local vault to that for the tests... but without mucking around with DNS/resolver I can't see a way to do that (and I don't want to do that)

Then I thought, why not just create an account and org just for integration testing.. which worked great except Github is too smart for that and invalidated my token when the code was checked in. (Great feature btw). 

So I'm at a loss at this point.. any guidance on this @sethvargo ?

Here's where I have been doing the work: https://github.com/parabuzzle/vault-ruby/tree/add_github_token_support

**Comment by sethvargo** [comment]
@parabuzzle you reached the point where I gave up :smile:. I don't have a good solution at this time until Vault supports custom GH endpoints.

**Comment by parabuzzle** [comment]
damnit.. I need this for an active project.. so I can just use my branch I guess... :(

issue on vault for adding custom GH endpoint support: https://github.com/hashicorp/vault/issues/572
