### ISSUE TITLE
Pathname expansion fails on systemd(x) or launchd(osx) serviced systems

### ISSUE THREAD

**Issue by kstruis** [hashicorp/vault-ruby#41]
lib/vault/defaults.rb:    `VAULT_DISK_TOKEN = Pathname.new("~/.vault-token").expand_path.freeze`

systemd doesn't expand '~' or provide HOME by design, so all Unix services (like chef-client) setups using this gem will fail and throw an exception with the following error : 
`  [2015-09-15T11:40:28+02:00] ERROR: couldn't find HOME environment -- expanding `~'`

changing it to `"#{ENV["HOME"]}/.vault-token"` will make sure it does not break on not finding a HOME variable.

**Comment by sethvargo** [comment]
Hi @kstruis 

Thank you for opening an issue. `ENV["VAULT_ADDR"]` is not the same as the home path though. VAULT_ADDR is the address where the vault server is running (which could be a remote IP).

**Comment by kstruis** [comment]
Hi Seth, 

Thank you for responding so soon!  Sorry, big typo/copypaste... I meant #{ENV["HOME"]} ofcourse.. updated the initial issue text.

**Comment by sethvargo** [comment]
https://github.com/hashicorp/vault-ruby/commit/0eb5d0498f4ca1b1841860f45526f1d6123b82fd
