### ISSUE TITLE
redirect causes URI parsing error

### ISSUE THREAD

**Issue by skippy** [hashicorp/vault-ruby#42]
Ruby 2.2.3
vault-ruby 0.1.5
vault 0.2

```
/usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:17:in `rescue in split': bad URI(is not URI?): http://10.0.12.202:8200/v1/secret/bc5eb597-4a93-4186-beee-e62e43242e2d/jwt_auth (URI::InvalidURIError)
  from /usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:14:in `split'
  from /usr/local/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
  from /usr/local/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:253:in `build_uri'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:123:in `request'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:218:in `block in request'
  from /usr/local/lib/ruby/2.2.0/net/http.rb:853:in `start'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:212:in `request'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/client.rb:87:in `put'
  from /usr/local/bundle/gems/vault-0.1.5/lib/vault/api/logical.rb:47:in `write'
```

I can trigger this pretty consistently against Vault 0.2 by hitting vault with the IP of a backup server (which then routes to the master) or by having an extra '/' in the url, such as `http://10.0.12.202:8200/v1//secret/bc5eb597-4a93-4186-beee-e62e43242e2d/jwt_auth`

Fixing this is easy, but I'm having a challenge recreating in dev... still working on it but I wanted to get this bug up there in case it was hitting other folks.

**Comment by skippy** [comment]
ah!  of course: https://github.com/hashicorp/vault-ruby/commit/67d215ef70d5e7dd7b7f79b411f259633746bf43#diff-814f188d3fb4dd3622ea413d271d5504R217

closing!

**Comment by skippy** [comment]
@sethvargo would you be willing to cut a 0.16 release?  I'm not sure how other folks aren't hitting this in a HA setup.  The moment I moved from a dev env with one instance of vault, to a staging env with vault setup with HA, this error cropped up.

**Comment by louism517** [comment]
+1 for a 0.1.6 release. Concur with @skippy - everything hunky-dory until moved Vault out of development (with HA enabled), then failures 50% of the time (we have 2 Vault servers). Took some time to figure out the problem, and now are running with a single Vault server.

**Comment by skippy** [comment]
@louism517 I've been using master keyed to a specific commit for 2 months now, in prod with 3 vault servers, and I haven't had any problems since.  

`gem 'vault', git: 'https://github.com/hashicorp/vault-ruby', ref: '0eb5d0498f4ca1b1841860f45526f1d6123b82fd'`

though I then ran into another issues with redirects and tls certificates...but that isn't a vault-ruby issue :)
