### ISSUE TITLE
make lease an explicit option during write

### ISSUE THREAD

**Issue by skippy** [hashicorp/vault-ruby#43]
hello,

at least from my reading of the docs, it isn't clear how to use lease with the ruby library.  I figured it out (it goes in the map that we want to save to vault), but I think it would be useful to explicitly call it out in the ruby API.  For example, instead of 

```ruby
::Vault.logical.write('secret/foo', {val: 'bar', lease: '1h'})
```

what if we did this:

```ruby
::Vault.logical.write('secret/foo', {val: 'bar'}, lease: '1h')
```

and add documentation that this is an option :)

of course, the old style would need to stick around for compatibility purposes, but I think this extra 'syntactic sugar' will help people use the lease option.

If that sounds reasonable, I'll submit a PR.

**Comment by sethvargo** [comment]
Hi @skippy,

The API is this:

```ruby
Vault.logical.write("secret/foo", opts)
```

The opts are the list of params to pass the HTTP query. They correspond to Vault's attributes for Vault's HTTP API directly. I don't particularly see the reason to make this a separate option although I'd be happy to add some docs for it.

```ruby
Vault.logical.write("secret/foo", val: "bar", lease: "1h")
```

is the correct syntax. I don't see the value in having two separate options hashes that ultimately get converted to the same URL params.

**Comment by skippy** [comment]
@sethvargo first off, thank you for taking the time to respond.

I'm not trying to go to the mattresses here. Let me throw out some food for thought, but no need to respond unless you want to dive in further. 

> is the correct syntax. I don't see the value in having two separate options hashes that ultimately get converted to the same URL params.

though I suspect most folks will end up doing this: 
```ruby
Vault.logical.write("secret/foo", data.merge(lease: "1h"))
```

This is mixing data and control parameters together.  It isn't the end of the world of course, and when there is just one, no problem.  But what about:
* multiple control parameters in the future?  perhaps a `disable_lease: true`
* what if secret backends end up having some of their own control parameters?  

Vault will end up with a list of reserved words, like this: https://github.com/jwt/ruby-jwt#support-for-reserved-claim-names.

not the end of the world, by any means, but I would put +1 behind separating out control and data params before the API gets too locked down.  Control params can go into the http header

ok, that's it.  I'll be quiet now unless you want to dive into this further :)

**Comment by jefferai** [comment]
I'm personally happy with having separate control and data option hashes
even if they go into the same data structure to the Vault server (for now).

One point: from Vault 0.3 on, please switch to using "ttl" instead of
lease. You probably already know this, just reminding you. :-)

--Jeff

**Comment by skippy** [comment]
@jefferai , the `ttl` change is a good call.  

So are you thinking that the vault server will, in the future, move control options out of the params/body/form and into the http header?

**Comment by jefferai** [comment]
There are no current plans to do so, and I think it more likely that the
current data structure would get split into two. Otherwise it could get
very complicated figuring out which headers to pass into which backends.
Plus if options are long you could risk making buffers unhappy if using a
reverse proxy.

**Comment by skippy** [comment]
@jefferai ok.  So... would you like me to submit a PR to split these options out or do you want to wait until this is hashed out in the larger vault ecosystem?  All things considered, I would be inclined to wait until the decision is made and set in stone, but I'll submit a PR if you want to go with it now.

**Comment by jefferai** [comment]
Up to you, but I think waiting is fine.
