### ISSUE TITLE
Support HA

### ISSUE THREAD

**Issue by bkeroackdsc** [hashicorp/vault-ruby#44]
Currently this client only supports specifying a single Vault server. Even if this client does the redirect automatically to the current master, it should allow specifying an array of servers and then try them in round-robin fashion.

**Comment by sethvargo** [comment]
@bkeroackdsc thank you for opening an issue. How do you have your Vault HA setup? In general we recommend putting the Vault leader and followers behind a load balancer. The followers will automatically forward write requests to the leader, but in Vault 0.3+ the followers will be able to respond to a limited number of requests.

As a matter of client libraries goes, I do not think it is a client library's responsibility to support HA. That is typically done at the infrastructure layer by using a load balancer or DNS round-robin. What do you think?

Side note - I'm a super early adopter of Dollar Shave Club and it has completely changed my life :smile:

**Comment by bkeroackdsc** [comment]
@sethvargo We are running Vault (current master) on three separate servers with the etcd backend (``vault-a.foo.com``, ``vault-b.foo.com``, ``vault-c.foo.com``). In testing, the inactive/standby nodes are doing 307 redirects to the advertised address of the current master.

It's not clear how a load balancer would be helpful here. If we had a LB at ``vault.foo.com`` with the three servers behind it (if my understanding is correct) we would have to set all advertised addresses to the same ``vault.foo.com``. Approximately 2/3 requests would then 307 redirect to itself (``vault.foo.com``) and the client would have to retry multiple times before hitting the current master.

(Thanks for the kind words regarding DSC! Shoot me an email at "benjamen" at the obvious domain and I'd be happy to hook you up with a sampler box of our new products.)

**Comment by jefferai** [comment]
> It's not clear how a load balancer would be helpful here. If we had a LB
at vault.foo.com with the three servers behind it (if my understanding is
correct) we would have to set all advertised addresses to the same
vault.foo.com. Approximately 2/3 requests would then 307 redirect to itself
(vault.foo.com) and the client would have to retry multiple times before
hitting the current master.

The bit Seth left out was behind a LB _performing status checks so it
always forwards to the current master_. Vault's (unauthenticated) status
endpoint can be used for this as the active and standby nodes return
different HTTP status codes.

--Jeff
