### ISSUE TITLE
Make client.rb read token from disk as a resort

### ISSUE THREAD

**Issue by bluecmd** [hashicorp/vault-ruby#45]
Hi,

I'm trying to use hiera-vault with a token file. I can see that the .vault-token file is read when running the software but I get this error:
/var/lib/gems/2.1.0/gems/vault-0.1.5/lib/vault/client.rb:313:in `error': Missing Vault token! I cannot make requests to Vault without a token. Please (Vault::MissingTokenError)

Would it be possible to use the token method in Defaults to get the token and thus fall back to the token on disk? Right now I have to apply sed magic to move the token to the configuration file, which isn't really nice since I want to keep the config in VCS.

Thanks for your consideration,

**Comment by sethvargo** [comment]
Hi @bluecmd 

Thank you for opening an issue. I am a bit confused. Are you storing your token in the environment or on disk? The `vault_token` method first attempts to read from disk and then falls back to the environment variable: https://github.com/hashicorp/vault-ruby/blob/0eb5d0498f4ca1b1841860f45526f1d6123b82fd/lib/vault/defaults.rb#L31-L39

**Comment by bluecmd** [comment]
Hi,

Yes, you're correct - the token function indeed already does that, and I can see in strace that the token is read. The problem is that the client.rb doesn't use this value, as far as I can tell and spits out the error that the token cannot be found.

Maybe this is an issue in hiera-vault, but I doubt it as the token is read, just not used.

[pid  1988] access("/root/.vault-token", R_OK) = 0
[pid  1988] open("/root/.vault-token", O_RDONLY|O_CLOEXEC) = 7
...
[pid  1988] read(7, "REDACTED"..., 36) = 36
[pid  1988] read(7, "", 8192)           = 0
[pid  1988] close(7)                    = 0
...
[pid  1988] write(2, "/var/lib/gems/2.1.0/gems/vault-0"..., 71/var/lib/gems/2.1.0/gems/vault-0.1.5/lib/vault/client.rb:313:in `error') = 71
[pid  1988] write(2, ": ", 2: )           = 2
[pid  1988] write(2, "Missing Vault token! I cannot ma"..., 76Missing Vault token! I cannot make requests to Vault without a token. Please) = 76
[pid  1988] write(2, " (", 2 ()           = 2
[pid  1988] write(2, "Vault::MissingTokenError", 24Vault::MissingTokenError) = 24
[pid  1988] write(2, ")\n", 2)

**Comment by sethvargo** [comment]
@bluecmd are you able to reproduce this issue with vault-ruby alone? I'm not familiar with vault-hiera or how it uses vault-ruby. 

The [defaults are set](https://github.com/hashicorp/vault-ruby/blob/0eb5d0498f4ca1b1841860f45526f1d6123b82fd/lib/vault/client.rb#L61) when the client is initialized.

**Comment by bluecmd** [comment]
Sorry, but I have no idea how to do that. The hiera-vault implementation is quite short, so maybe it's easy to spot if anything is wrong:
https://github.com/jsok/hiera-vault/blob/master/lib/hiera/backend/vault_backend.rb

**Comment by sethvargo** [comment]
This is a bug in vault-hiera. [On this line](https://github.com/jsok/hiera-vault/blob/076482eb52da70b3bfe7c418412cfc402403749d/lib/hiera/backend/vault_backend.rb#L18), there is no check to ensure the config token has an actual value, so it's being overwritten with (presumably) an empty string or nil.

Please open an issue on that project.

**Comment by sethvargo** [comment]
In fact, it's already reported. It's slightly different, but it's the same root cause: https://github.com/jsok/hiera-vault/issues/5

**Comment by bluecmd** [comment]
Ah, that makes sense! Thanks for helping me pin-point this. Sorry for the noise.
