### ISSUE TITLE
Can't Retrieve Secret Key Attribute With String

### ISSUE THREAD

**Issue by jcderose** [hashicorp/vault-ruby#52]
I'm running Vault 0.3.1 and am trying to retrieve secrets for my Chef recipe via the vault-ruby gem. My recipe is set up as follows:

```
Vault.address = 'fqdn-for-vault'
Vault.auth.app_id(
  'vault_app_id',
  'vault_user_id'
)
variable = 'my-attribute'
node.default['my-attribute'] = Vault.logical.read("secret/my-secret").data["#{variable}"]
```
This retrieves nothing from Vault. 

However, the following code retrieves the data correctly:

```
node.default['my-attribute'] = Vault.logical.read("secret/my-secret").data[:my-attribute]
```

Note the use of a symbol instead of a string. For my use case, the `:my-attribute` value changes depending on certain dynamic criteria in the Chef environment so I can't use hard-coded symbols. Is there any way to reference a variable (or a string) when pulling from the `Vault.logical.read().data[]` hash, rather than using a symbol?

Thanks!

**Comment by sethvargo** [comment]
Hi @jcderose 

You can put a colon in front of your key:

```ruby
.data[:"#{variable}"]
```

or call `.to_sym`:

```ruby
.data[variable.to_sym]
```
