### ISSUE TITLE
Root token is set automatically

### ISSUE THREAD

**Issue by rthulasingam** [hashicorp/vault-ruby#71]
I created a new client in rails project using following command

client_1 = Vault::Client.new(address: http://127.0.0.1:8200")

I am surprised to see the root token automatically assigned in the secret. how this even possible?

**Comment by sethvargo** [comment]
Hi @rthulasingam 

The root token can come from two places:

- ~/.vault-token
- ENV["VAULT_TOKEN"]

You have one of those set, somewhere.

Please let me know if you have any questions.
