### ISSUE TITLE
get the local env variables if don't find one on vault

### ISSUE THREAD

**Issue by kaiomagalhaes** [hashicorp/vault-ruby#76]
Hey guys, I need a way to get a local env variable if I don't have one on the server. I've have implemented it on my project and I'm willing to setup it here.

The plan would be to enable it here:
```
Vault.configure do |config|
   config.enable_local_envs = true
end
```

Do you guys agree?

**Comment by sethvargo** [comment]
Hey @kaiomagalhaes 

Thank you for opening an issue. Please keep in mind that "guys" is a gender-specific pronoun that doesn't include all the employees at HashiCorp 😄 . 

The Vault Ruby library should read the VAULT_TOKEN environment variable. Are you seeing different behavior?

**Comment by sethvargo** [comment]
Closing due to lack of response.
