### ISSUE TITLE
Unable to Wrap/Unwrap to transit secret backend

### ISSUE THREAD

**Issue by grempe** [hashicorp/vault-ruby#83]
I am trying to re-create the following sequence, which uses the vault CLI, using the vault-ruby gem.

Write to a backend, passing in the `-wrap-ttl="5m"` param which sends the `X-Vault-Wrap-TTL` HTTP header that triggers wrapping of the response.
```
~/src$ echo -n "the quick brown fox" | base64 | vault write -wrap-ttl="5m" transit/encrypt/foo plaintext=-
Key                            	Value
---                            	-----
wrapping_token:                	bd83180d-e693-69ee-0016-54d075973c2d
wrapping_token_ttl:            	300
wrapping_token_creation_time:  	2016-08-14 04:57:33.61304149 +0000 UTC
```

Use the returned one-time use token to get the response from the cubbyhole it was stored in:
```
~/src$ vault unwrap bd83180d-e693-69ee-0016-54d075973c2d
Key            	Value
---            	-----
ciphertext     	vault:v1:rURgCIgfc9I0S6T6qWJolfHXpxY2hpDokkE6BqX7Uj23ObTxz+ehnzjx1I4Hf+0=
```

Decrypt the returned ciphertext from the cubbyhole:
```
~/src$ vault write transit/decrypt/foo ciphertext="vault:v1:rURgCIgfc9I0S6T6qWJolfHXpxY2hpDokkE6BqX7Uj23ObTxz+ehnzjx1I4Hf+0="
Key            	Value
---            	-----
plaintext      	dGhlIHF1aWNrIGJyb3duIGZveA==
```

Base64 decode the plaintext to use it.
```
~/src$ echo 'dGhlIHF1aWNrIGJyb3duIGZveA==' | base64 -d
the quick brown fox%
```

### But in Ruby...

I cannot figure out how to do step 1, writing the secret and sending the equivalent to `-wrap-ttl="5m"`. 

`Vault.logical.write` does not seem to have a way to pass on this wrapping header.

https://github.com/hashicorp/vault-ruby/blob/c21189f00a0b2c6c5eba04ff2eab968ba9b00fb8/lib/vault/api/logical.rb#L64

Am I missing something, or is it kind of impossible at the moment to write and wrap a secret in one step?

**Comment by sethvargo** [comment]
Hi @grempe 

Thank you for opening an issue. Wrap-TTLs are relatively new in Vault, and the Ruby library currently only supports wrap-TTLs for tokens.

**Comment by sethvargo** [comment]
I'm also a bit confused as to why you want to wrap the encrypted ciphertext at all? This is something we will support in the Vault Ruby library, but you're not getting any additional security by wrapping the _encrypted_ response.

**Comment by grempe** [comment]
Thanks @sethvargo for the quick response.

I guess I am just experimenting and trying to wrap my head around how to use secret wrapping.  I'm finding the docs a bit opaque on this topic.

https://www.vaultproject.io/docs/concepts/response-wrapping.html
https://www.vaultproject.io/docs/secrets/cubbyhole/index.html

What I'm trying to accomplish is to write a secret to a back-end (whichever is best for the job) and be given back a one-time use token to retrieve it later.  I tried using the -wrap-ttl with the generic secret backend using the CLI but it seemed to not work.  Hence my transit example.

I'd love to see more exploration (blog post?) of some use cases for secret wrapping.

I'll try out your enhancements today.

Cheers

PS - a new release to Rubygems soon would be useful. I think the last was five months ago and lots of things on master are missing.  Using a :git ref in Gemfile, but thats always a bit icky. :-)

**Comment by grempe** [comment]
Hi again @sethvargo 

Here is a quick example I got working with your latest commits just to follow up on my original post.  This is the only example I've been able to get to work. I ran this with Pry so you can see more details of what is in each response.

```ruby
[32] pry(main)> wrapped = Vault.logical.write("transit/encrypt/foo", {plaintext: Base64.encode64('foo')}, {wrap_ttl: '10m'})
=> #<Vault::Secret:0x007fd529941910
 @auth=nil,
 @data=nil,
 @lease_duration=0,
 @lease_id="",
 @renewable=false,
 @warnings=nil,
 @wrap_info=
  #<Vault::WrapInfo:0x007fd5299413e8
   @creation_time=2016-08-14 18:53:13 UTC,
   @token="6387b42e-2b47-3031-1796-5efeefa73362",
   @ttl=600,
   @wrapped_accessor=nil>>

[33] pry(main)> unwrapped = Vault.logical.unwrap(wrapped.wrap_info.token)
=> #<Vault::Secret:0x007fd52c9e8a50
 @auth=nil,
 @data={:ciphertext=>"vault:v1:64OmQL4QKPvg5GR4DlZlqmzQlZoKH+GGkJyHW5dWoQ=="},
 @lease_duration=0,
 @lease_id="",
 @renewable=false,
 @warnings=nil,
 @wrap_info=nil>

[34] pry(main)> decrypted = Vault.logical.write("transit/decrypt/foo", {ciphertext: unwrapped.data[:ciphertext]})
=> #<Vault::Secret:0x007fd52c950f48
 @auth=nil,
 @data={:plaintext=>"Zm9v"},
 @lease_duration=0,
 @lease_id="",
 @renewable=false,
 @warnings=nil,
 @wrap_info=nil>

[35] pry(main)> puts Base64.decode64(decrypted.data[:plaintext])
foo
=> nil
```

If I try to write to any secret backend other than `transit` passing in the `{wrap_ttl: '10m'}` options seems to have no effect.  Should it work on any backends other than transit?

I think you are right that this is a strange example, since I am storing transit encrypted data inside a cubbyhole. But its the only thing I could get to work.

I guess that perhaps the more straightforward way to accomplish what I was seeking above is to just forget about wrapping and:

- create a new token with only 1 time use allowed and a 24 hour expiration
- write my key/value data into a cubbyhole using that token
- pass that 1 time use token to the recipient (somehow, perhaps stored in a common 'secrets/common_cubbyhole_key_name' generic backend for easy retrieval)
- later (within the 24 exp time), lookup that one time use token in its common location and use it to retrieve the stored data from the cubbyhole. It can no longer be retrieved if that request is replayed again (or if after the original 24 hour time).

If you have any other ideas I'm happy to hear them.  Thanks again.
