### ISSUE TITLE
v. 0.5.0 compatibility vs 0.4.0 

### ISSUE THREAD

**Issue by Mykolaichenko** [hashicorp/vault-ruby#85]
Hi
we have this constructions in our code: 

```
creds = Vault.logical.read("bla/devops/base64")
creds =creds['data'][:auth1].split(':')
```

in v.0.4.0 its working 
but in new version - not 

how we may change out code to make it working? 
tnx

**Comment by sethvargo** [comment]
Can you share more information? What isn't working? Are you getting an error? What does the error say?

**Comment by brandonwestcott** [comment]
Just ran into this as well - it appears that [previously `Vault::Secret` was a struct](https://github.com/hashicorp/vault-ruby/blob/v0.4.0/lib/vault/api/secret.rb#L5), allowing the hash like access. In 0.5.0, it doesn't appear the `[]` or `[]=` methods are implemented in the new struct'less `Vault::Response`

**Comment by sethvargo** [comment]
Oh yea - you shouldn't have been using `['data']` - it should be `.data`
