### ISSUE TITLE
authentication issue with Vagrant 1.8.5 version

### ISSUE THREAD

**Issue by tanujchinnu** [hashicorp/vault-ruby#86]
I'm using Vagrant 1.8.5 and I'm having this issue and I'm using virtual box 5.0.22

    appnode: Inserting generated public key within guest...
    appnode: Removing insecure key from the guest if it's present...
    appnode: Key inserted! Disconnecting and reconnecting using new SSH key...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
    appnode: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by sethvargo** [comment]
This is not Vagrant. Please open an issue in the appropriate repo. Thanks!
