### ISSUE TITLE
CGI.escape on LDAP groups

### ISSUE THREAD

**Issue by reppard** [hashicorp/vault-ruby#95]
Basically what I am running into is I can't use this library to write ldap group policy mappings because CGI.escape subs out spaces and replace them with '+'.  This results in no groups being found for a user.  If I post to this path(auth/ldap/groups/) via the vault CLI things work as expected.  Looking for a work around at the very least.

```irb
irb(main):007:0> client.logical.write("auth/ldap/groups/\"Test Group\"", policies: 'test-policy')
=> true
irb(main):008:0> client.logical.list('auth/ldap/groups')
=> ["\"Test+Group\""]
```

**Comment by tomalok** [comment]
FWIW, it works when using the `vault` CLI...  If that's sufficient as a "workaround"...
```
vault write auth/ldap/groups/"Group with Spaces" policies=test-policy
```

**Comment by reppard** [comment]
@tomalok that is what I ended up doing in the meantime.  I have some Rake tasks configuring vault via this sdk and for the ldap group mappings I ended up just making system calls from my rake file.  Works for now but it is not ideal.  Ideally all the configuration could be done without calling the vault CLI from my Rakefile.

**Comment by reppard** [comment]
Thanks for patching this @evanphx and @sethvargo thank for all your work on this library.  I'll test these fixes out in the next day or so. :heart:
